### PR TITLE
Update gawk-version to 5.2.2 from 5.1.1

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Comment by IgorTodorovskiIBM** [comment]
Thanks @v1gnesh !!!

**Comment by v1gnesh** [comment]
@IgorTodorovskiIBM - what do you think about doing ron tests automatically when a 'zosopentoolsmain' opens a PR?
The bump action could be updated to say **ron tests** in the PR comment body too.

**Comment by IgorTodorovskiIBM** [comment]
> @IgorTodorovskiIBM - what do you think about doing ron tests automatically when a 'zosopentoolsmain' opens a PR? The bump action could be updated to say **ron tests** in the PR comment body too.

Yep, actually I made some updates to the github action. Going forward, the build and run github action will be run whenever a PR is opened as well

**Comment by MikeFultonDev** [comment]
Do we have a notion of priority or server routing so that important build break builds will get priority on our systems over a lower priority (potentially) run that is a bump and also a higher priority bump build to pick up a cve ? Or - do we have enough servers that routing to a free machine is still ‘good enough’?

**Comment by v1gnesh** [comment]
Seeing the failures, and seeing how the time is captured in the Action, I think it'll be good to check where we are w.r.t the free tier limits on Actions usage for the org.
Although the build isn't running in the "machine" running the Action itself, the Action-running "machine" is still up and ticking.

Priority queueing is a good thing to have. Will see if the other CI :wink: has any workflows for this.

**Comment by v1gnesh** [comment]
The build logs also have some funny stuff:

```shell
 ++ zopen upgrade meta -y
�����`�>ŀ��_?������?��?ʀ%/���Ȁ�/�,/����>�?�_/��?>�Installing package: meta
Package meta is already installed at the requested version: main.20231022_024501

++ zopen build -v -b release -u -gp --no-set-active
����|� �����>ŀ���%���?����<��Checking environment configuration


����/�Ȁ�/��/%%��/�,��/��:��>�?��/�,���/�>�>Ś��>������?�,�>ŀ�?�`�?À����>��?>��������<���%%�������%/�����`�<�����>��Ȁ��_����Ȁ�?����ˀ�Ȏ�/�>�>Ś��>������?�,�>ŀ�?�`�?À���/�,�������<���%%�������%/�����`�<�����>��Ȁ��_����Ȁ�?����ˀ�Ȏ�/�>�>Ś��>������?�,�>ŀ�?�`�?À��_/,��?>����/�����<���%%�������%/�����`�<�����>��Ȁ��_����Ȁ�?����ˀ�Ȏ�/�>�>Ś��>������?�,�>ŀ�?�`�?À������%�/�,����<���%%�������%/�����`�<�����>��Ȁ��_����Ȁ�?����ˀ�Ȏ�/�>�>Ś��>������?�,�>ŀ�?�`�?À����>���/>��/�,����<���%%�������%/�����`�<�����>��Ȁ��_����Ȁ�?����ˀ�Ȏ���%`�>ŀ�/����ˎVERBOSE: 'Using patch directory /jenkins/PortBuild/gawk/patches'
```

**Comment by IgorTodorovskiIBM** [comment]
> Do we have a notion of priority or server routing so that important build break builds will get priority on our systems over a lower priority (potentially) run that is a bump and also a higher priority bump build to pick up a cve ? Or - do we have enough servers that routing to a free machine is still ‘good enough’?

Not at this time, we can take that on as a separate todo. We currently have 6 separate CI WaaS machines. We'll see how that fares.

The garbled messages has been a long standing issue with the Jenkins runs, now is probably a good time to investigate.

**Pull request merged**
